In [71]:
import numpy as np

In [72]:
# amostras = np.array([
#     np.array([-1, 2, 3.5]), 
#     np.array([-1, 6.8, 5.3]), 
#     np.array([-1, 2, 2.5]),
#     np.array([-1, 8.1, 4.2]),
# ])

# saidas_desejadas = np.array([-1, 1, -1, 1])

# amostras = np.array([
#     np.array([-1, -1, -1]), 
#     np.array([-1, -1, 1]), 
#     np.array([-1, 1, -1]),
#     np.array([-1, 1, 1]),
# ])

# saidas_desejadas = np.array([-1, 1, 1, 1])


bias = 1
bias_weight = 0.7

amostras = np.array([
    np.array([bias, 0.2, -4]),
    np.array([bias, -1.1, 2]),
    np.array([bias, 2, 0.8]),
    np.array([bias, -1, 1.2]),
])
saidas_desejadas = np.array([0, 1, 0, 1])


In [73]:
# w = np.random.rand(len(amostras[0])) * 0.1 # pesos iniciais aleatórios pequenos

# w = np.array([bias_weight, -0.3, 0.2])

w = np.array([ 0.6 , -0.5,   0.12])

print(f"Pesos iniciais: {w}")

Pesos iniciais: [ 0.6  -0.5   0.12]


In [74]:
# Taxa de aprendizado
eta = 0.1

# Número máximo de épocas
max_epocas = 10

In [75]:
pares_treinamento = list(zip(amostras, saidas_desejadas))

epocas = 1

In [76]:
def function_phi(v):
    # 0 se v < 0, 1 se v >= 0
    return 1 if v >= 0 else 0

In [77]:
while epocas <= max_epocas:
    print("-"*10)
    print(f"Época: {epocas}")
    erro = False
    for par in pares_treinamento:
        x, d = par
        print(f"Amostra: {x} - Saída desejada: {d}")
        # print de x*w por extenso
        v = np.dot(x, w) # x0 * w0 + x1 * w1 + x2 * w2
        print(f"{x} * {w} = {v}")
        y = function_phi(v)
        print(f"Saída: {y} é igual a {d}? {'Sim' if y == d else 'Não é igual! Vamos corrigir...'}")
        if y != d:
            erro = True
            delta_w = eta * (d - y) * x
            w = w + delta_w
            print(f"Pesos atualizados: {w}")
    if not erro:
        break
    epocas += 1

print(f"Pesos finais: {w}")
print(f"Número de épocas: {epocas}")

----------
Época: 1
Amostra: [ 1.   0.2 -4. ] - Saída desejada: 0
[ 1.   0.2 -4. ] * [ 0.6  -0.5   0.12] = 0.020000000000000018
Saída: 1 é igual a 0? Não é igual! Vamos corrigir...
Pesos atualizados: [ 0.5  -0.52  0.52]
Amostra: [ 1.  -1.1  2. ] - Saída desejada: 1
[ 1.  -1.1  2. ] * [ 0.5  -0.52  0.52] = 2.112
Saída: 1 é igual a 1? Sim
Amostra: [1.  2.  0.8] - Saída desejada: 0
[1.  2.  0.8] * [ 0.5  -0.52  0.52] = -0.124
Saída: 0 é igual a 0? Sim
Amostra: [ 1.  -1.   1.2] - Saída desejada: 1
[ 1.  -1.   1.2] * [ 0.5  -0.52  0.52] = 1.6440000000000001
Saída: 1 é igual a 1? Sim
----------
Época: 2
Amostra: [ 1.   0.2 -4. ] - Saída desejada: 0
[ 1.   0.2 -4. ] * [ 0.5  -0.52  0.52] = -1.6840000000000002
Saída: 0 é igual a 0? Sim
Amostra: [ 1.  -1.1  2. ] - Saída desejada: 1
[ 1.  -1.1  2. ] * [ 0.5  -0.52  0.52] = 2.112
Saída: 1 é igual a 1? Sim
Amostra: [1.  2.  0.8] - Saída desejada: 0
[1.  2.  0.8] * [ 0.5  -0.52  0.52] = -0.124
Saída: 0 é igual a 0? Sim
Amostra: [ 1.  -1.   1.2] - S